// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoH7yHX-xWGgbbJ4xm_CQCykU--r4D_ac',
    appId: '1:638760988678:web:473a9e583e4961c1695387',
    messagingSenderId: '638760988678',
    projectId: 'utsproject-d1d44',
    authDomain: 'utsproject-d1d44.firebaseapp.com',
    storageBucket: 'utsproject-d1d44.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOYzcO2_bpSqK-oXVJbcqSx9Mu0pk-C5g',
    appId: '1:638760988678:android:884a6c70c4401ec9695387',
    messagingSenderId: '638760988678',
    projectId: 'utsproject-d1d44',
    storageBucket: 'utsproject-d1d44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu3GYutnUsRQickLyyQoZfQKWULWJrC18',
    appId: '1:638760988678:ios:0f11bb38c5fa9a2d695387',
    messagingSenderId: '638760988678',
    projectId: 'utsproject-d1d44',
    storageBucket: 'utsproject-d1d44.firebasestorage.app',
    iosBundleId: 'com.example.flutterAiAssistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu3GYutnUsRQickLyyQoZfQKWULWJrC18',
    appId: '1:638760988678:ios:0f11bb38c5fa9a2d695387',
    messagingSenderId: '638760988678',
    projectId: 'utsproject-d1d44',
    storageBucket: 'utsproject-d1d44.firebasestorage.app',
    iosBundleId: 'com.example.flutterAiAssistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoH7yHX-xWGgbbJ4xm_CQCykU--r4D_ac',
    appId: '1:638760988678:web:af1a34afa8cbff72695387',
    messagingSenderId: '638760988678',
    projectId: 'utsproject-d1d44',
    authDomain: 'utsproject-d1d44.firebaseapp.com',
    storageBucket: 'utsproject-d1d44.firebasestorage.app',
  );
}
